# Please adapt to package name:
# rename the file name to match the
# "prefix" configured in the config
# module
host: 127.0.0.1
port: 8080
log_level: info
workers: 1
auto_reload: true
db_url: mongodb://localhost:27017
db_name: metadata-store
api_root_path: "/"
openapi_url: "/openapi.json"
docs_url: "/docs"
schema_url: https://raw.githubusercontent.com/ghga-de/ghga-metadata-schema/0.7.0/src/schema/ghga.yaml
creation_schema_url: https://raw.githubusercontent.com/ghga-de/ghga-metadata-schema/0.7.0/artifacts/derived_schema/creation/ghga_creation.yaml
